# Generated by Django 5.2.6 on 2025-09-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed product', max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(choices=[('apparel & gear', 'Apparel & Gear'), ('equipment', 'Equipment'), ('accessories', 'Accessories')], default='equipment', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField()),
                ('is_featured', models.BooleanField()),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
