# Generated by Django 5.2.6 on 2025-09-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
